import { createFileRoute, useNavigate } from '@tanstack/react-router';
import { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { lovable } from '@/integrations/lovable';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import { pageHead } from '@/lib/prescribly-content';
export const Route=createFileRoute('/auth')({head:()=>pageHead('/auth','Team sign in','Private sign in for the Prescribly Events team.',true),component:Auth});
function Auth(){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const navigate=useNavigate();async function signIn(e:React.FormEvent){e.preventDefault();setBusy(true);const {data,error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error||!data.user){toast.error('Sign in failed. Check your details.');return}const {data:isAdmin}=await supabase.rpc('has_role',{_user_id:data.user.id,_role:'admin'});const {data:isEditor}=await supabase.rpc('has_role',{_user_id:data.user.id,_role:'editor'});if(!isAdmin&&!isEditor){await supabase.auth.signOut();toast.error('This account does not have team access.');return}navigate({to:'/admin'})}return <div className="mx-auto flex min-h-[70vh] max-w-lg items-center px-5 py-20"><div className="w-full border border-border bg-card p-7"><p className="text-xs font-bold uppercase text-primary">Prescribly Events</p><h1 className="mt-4 text-3xl font-bold">Team sign in</h1><p className="mt-3 text-sm text-muted-foreground">Private access for approved administrators and editors.</p><form onSubmit={signIn} className="mt-8 space-y-4"><label className="block text-sm font-semibold">Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 block w-full border border-input bg-background px-3 py-3"/></label><label className="block text-sm font-semibold">Password<input required type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 block w-full border border-input bg-background px-3 py-3"/></label><Button className="w-full" disabled={busy}>{busy?'Signing in...':'Sign in'}</Button></form><div className="my-5 flex items-center gap-3 text-xs text-muted-foreground"><span className="h-px flex-1 bg-border"/>or<span className="h-px flex-1 bg-border"/></div><Button variant="outline" className="w-full" onClick={()=>lovable.auth.signInWithOAuth('google',{redirect_uri:`${window.location.origin}/auth`})}>Continue with Google</Button></div></div>}
