import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { useServerFn } from '@tanstack/react-start';
import { z } from 'zod';
import { Send } from 'lucide-react';
import { sendContactMessage } from '@/lib/public-submissions.functions';
import { toast } from 'sonner';
import { PageIntro, SectionHeading } from '@/components/SectionUI';
import { Button } from '@/components/ui/button';
import { pageHead } from '@/lib/prescribly-content';
import hero from '@/assets/prescribly-events-hero.jpg';
const interests=['Event Registration','Sponsorship','Partnership','Speaking','Volunteering','Media','Campaigns','General Enquiry'] as const;
const schema=z.object({name:z.string().trim().min(1),email:z.email(),phone:z.string().max(40),organization:z.string().max(150),interest:z.enum(interests),message:z.string().trim().min(5).max(2000)});
export const Route=createFileRoute('/contact')({head:()=>pageHead('/contact','Contact Prescribly Events','Contact the Prescribly Events team about registration, sponsorship, partnerships, speaking, volunteering and campaigns.'),component:Contact});
function Contact(){const send=useServerFn(sendContactMessage);const [form,setForm]=useState({name:'',email:'',phone:'',organization:'',interest:'General Enquiry' as typeof interests[number],message:''});const [busy,setBusy]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();const parsed=schema.safeParse(form);if(!parsed.success){toast.error('Please complete all required fields.');return}setBusy(true);try{const result=await send({data:parsed.data});setBusy(false);if(!result.ok){toast.error('Could not send your message. Please try again.');return}toast.success('Your message has been sent.');setForm({name:'',email:'',phone:'',organization:'',interest:'General Enquiry',message:''})}catch{setBusy(false);toast.error('Could not send your message. Please check your details and try again.')}}return <div><PageIntro eyebrow="Contact" title="LET'S START A CONVERSATION." description="Events, partnerships, speaking, volunteering or campaigns — reach the Prescribly Events team." image={hero}/><section className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[.7fr_1.3fr]"><div><SectionHeading eyebrow="Talk to us" title="How can we work together?"/><p className="mt-7 text-sm text-muted-foreground">Prescribly Events<br/>Abuja, Nigeria</p><a href="https://prescribly.app" className="mt-4 block text-sm font-bold text-primary">prescribly.app ↗</a></div><form onSubmit={submit} className="grid gap-5 border border-border bg-card p-6 sm:grid-cols-2 sm:p-8">{[['Name','name'],['Email','email'],['Phone','phone'],['Organization','organization']].map(([label,key])=><label key={key} className="text-sm font-semibold">{label}{['name','email'].includes(key)?' *':''}<input required={['name','email'].includes(key)} type={key==='email'?'email':'text'} value={form[key as keyof Pick<typeof form,'name'|'email'|'phone'|'organization'>]} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-2 block w-full border border-input bg-background px-3 py-3"/></label>)}<label className="text-sm font-semibold sm:col-span-2">Interest *<select value={form.interest} onChange={e=>setForm({...form,interest:e.target.value as typeof form.interest})} className="mt-2 block w-full border border-input bg-background px-3 py-3">{interests.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-semibold sm:col-span-2">Message *<textarea required rows={6} value={form.message} onChange={e=>setForm({...form,message:e.target.value})} className="mt-2 block w-full border border-input bg-background px-3 py-3"/></label><Button className="sm:col-span-2" disabled={busy}><Send/>{busy?'Sending...':'Send Message'}</Button></form></section></div>}
