import { createFileRoute, Link } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { useServerFn } from '@tanstack/react-start';
import { getPublicContent } from '@/lib/public-data.functions';
import { TARGETS, pageHead } from '@/lib/prescribly-content';
import { PageIntro, SectionHeading } from '@/components/SectionUI';
import { Button } from '@/components/ui/button';
import community from '@/assets/community-health.jpg';
const labels=['People Reached','Health Screenings','Women Reached','Students Engaged','Events','Campaigns','Volunteers','Partners'];
export const Route=createFileRoute('/impact')({head:()=>pageHead('/impact','Impact and event targets','See verified Prescribly Events figures separately from the 2027 Kaduna event targets.'),component:Impact});
function Impact(){const [metrics,setMetrics]=useState<Awaited<ReturnType<typeof getPublicContent>>['metrics']>([]);const fetchData=useServerFn(getPublicContent);useEffect(()=>{fetchData().then(d=>setMetrics(d.metrics)).catch(()=>{});},[fetchData]);return <div><PageIntro eyebrow="Our impact" title="MEASURING WHAT MATTERS." description="A clear view of reported progress, with ambitions kept separate from results." image={community}/><section className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><SectionHeading eyebrow="Reported impact" title="Progress, not promises." copy="These figures are editable by the Prescribly team. A zero means no verified result has been published yet."/><div className="mt-10 grid gap-px bg-border sm:grid-cols-2 lg:grid-cols-4">{labels.map(label=>{const metric=metrics.find(m=>m.label===label&&m.metric_type==='achieved');return <div key={label} className="min-h-36 bg-background p-6"><strong className="text-4xl font-black text-primary">{Number(metric?.value??0).toLocaleString()}{metric?.suffix??''}</strong><p className="mt-4 text-sm font-semibold text-muted-foreground">{label}</p></div>})}</div></section><section className="bg-secondary"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><SectionHeading eyebrow="2027 event targets · not achieved" title="Kaduna: the goals ahead." copy="The numbers below are targets for Kaduna Digital Health & Wellness Week 2027, not completed achievements."/><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{TARGETS.map(([value,label])=><div key={label} className="border-t-4 border-primary bg-card p-5"><strong className="text-3xl font-bold">{value}</strong><p className="mt-4 text-sm text-muted-foreground">{label}</p></div>)}</div><Button asChild variant="outline" className="mt-8"><Link to="/events/kaduna-digital-health-wellness-week-2027">Explore the event</Link></Button></div></section><section className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><SectionHeading eyebrow="Campaign reporting" title="PadAndFresh support" copy="The campaign’s donation record remains available as part of the wider Prescribly ecosystem."/><Button asChild className="mt-8"><Link to="/campaigns/padandfresh">Explore PadAndFresh</Link></Button></section></div>}
