import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowRight, ArrowUpRight, CalendarDays, MapPin, MoveUpRight } from 'lucide-react';
import hero from '@/assets/prescribly-events-hero.jpg';
import community from '@/assets/community-health.jpg';
import { PILLARS, TARGETS, pageHead } from '@/lib/prescribly-content';
import { Button } from '@/components/ui/button';
import { SectionHeading, EventCard, FeatureGrid } from '@/components/SectionUI';
export const Route = createFileRoute('/')({head:()=>pageHead('/','Healthcare conversations, communities and impact','Prescribly Events connects healthcare professionals, innovators and communities to shape better healthcare in Africa.'),component:Home});
function Home() { return <div><section className="relative isolate min-h-[610px] overflow-hidden bg-foreground text-primary-foreground sm:min-h-[690px]"><img src={hero} width={1600} height={1008} alt="Healthcare professionals and innovators in conversation at an African health event" className="absolute inset-0 h-full w-full object-cover object-center"/><div className="absolute inset-0 bg-foreground/70"/><div className="relative mx-auto flex min-h-[610px] max-w-7xl flex-col justify-center px-5 py-20 sm:min-h-[690px] sm:px-8"><span className="text-xs font-bold uppercase text-signal">A Prescribly Initiative</span><h1 className="mt-7 max-w-4xl text-4xl font-black leading-tight sm:text-6xl lg:text-7xl">THE FUTURE OF HEALTHCARE STARTS WITH A CONVERSATION.</h1><p className="mt-7 max-w-2xl text-base leading-relaxed text-primary-foreground/90 sm:text-lg">Prescribly Events brings together healthcare professionals, innovators, communities, young people, organizations and changemakers to explore the ideas shaping the future of healthcare in Africa.</p><p className="mt-3 max-w-2xl text-base leading-relaxed text-primary-foreground/80">From digital health and artificial intelligence to women's health, preventive care and community outreach, we create spaces where people connect, learn and turn conversations into action.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg" className="h-12 bg-signal px-6 text-foreground hover:bg-signal/90"><Link to="/events">Explore Events <ArrowUpRight /></Link></Button><Button asChild size="lg" variant="outline" className="h-12 border-primary-foreground/70 bg-transparent px-6 text-primary-foreground hover:bg-primary-foreground/15 hover:text-primary-foreground"><Link to="/community">Join the Community <ArrowRight /></Link></Button></div></div></section>
<section className="border-b border-border bg-card"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-5 py-5 text-xs font-semibold uppercase text-muted-foreground sm:px-8"><span>Conversations</span><span>Communities</span><span>Healthcare</span><span>Impact</span><span className="text-primary">Across Africa</span></div></section>
<section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="Our next big event" title="A new chapter for health in Kaduna." copy="Three days of conversations, community health and opportunities for the next generation."/><EventCard title="Kaduna Digital Health & Wellness Week 2027" subtitle="Healthy Communities. Digital Innovation. Better Healthcare." category="Flagship event · 2027" location="Kaduna, Nigeria" href="/events/kaduna-digital-health-wellness-week-2027" status="Registration coming soon"/></div><div className="mt-8 flex flex-wrap gap-3"><Button asChild><Link to="/events/kaduna-digital-health-wellness-week-2027">Explore the Event <ArrowRight /></Link></Button><Button asChild variant="outline"><Link to="/partners">Become a Partner</Link></Button></div></section>
<section className="bg-secondary"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-2 lg:gap-20"><div><span className="text-xs font-bold uppercase text-primary">Why Prescribly Events</span><h2 className="mt-4 text-4xl font-bold leading-tight sm:text-5xl">Healthcare Is Bigger Than an App.</h2></div><div className="space-y-4 text-lg leading-relaxed text-secondary-foreground"><p>Technology can connect a patient to a doctor. But transforming healthcare requires more.</p><p>It requires education. It requires community. It requires collaboration. It requires people willing to have difficult conversations, share knowledge and build solutions.</p><p>Prescribly Events exists to create those spaces. We bring people together around healthcare challenges that matter and create opportunities to move from conversation to action.</p></div></div></section>
<section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><SectionHeading eyebrow="What we do" title="Different spaces. Shared purpose." copy="An ecosystem designed for learning, connection and meaningful participation."/><div className="mt-10"><FeatureGrid items={PILLARS}/></div></section>
<section className="bg-foreground text-primary-foreground"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-2 lg:items-center"><div><span className="text-xs font-bold uppercase text-signal">Beyond the screen</span><h2 className="mt-4 text-4xl font-bold sm:text-5xl">Healthcare belongs in every community.</h2><p className="mt-5 max-w-xl text-primary-foreground/75">Explore our campaigns in women's health, community health, youth and digital health, and PadAndFresh.</p><Button asChild size="lg" className="mt-8 bg-signal text-foreground hover:bg-signal/90"><Link to="/campaigns">Explore Campaigns <ArrowRight /></Link></Button></div><img src={community} alt="Healthcare workers providing a community wellness screening" width={1408} height={912} loading="lazy" className="aspect-[4/3] w-full object-cover"/></div></section>
<section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><div className="flex flex-wrap items-end justify-between gap-6"><SectionHeading eyebrow="2027 event targets" title="An ambition for Kaduna." copy="These are targets for Kaduna Digital Health & Wellness Week 2027, not completed results."/><Link to="/impact" className="flex items-center gap-2 text-sm font-bold text-primary">See our approach <MoveUpRight className="size-4" /></Link></div><div className="mt-10 grid gap-px bg-border sm:grid-cols-2 lg:grid-cols-5">{TARGETS.map(([number,label])=><div key={label} className="bg-background p-5"><strong className="block text-3xl font-black text-primary">{number}</strong><span className="mt-3 block text-sm text-muted-foreground">{label}</span></div>)}</div></section>
<section className="border-t border-border bg-card"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-20 sm:px-8 lg:grid-cols-3"><div><span className="text-xs font-bold uppercase text-primary">Get involved</span><h2 className="mt-4 text-3xl font-bold">The conversation needs you.</h2></div>{[['Join the community','Connect with people working towards better healthcare.','/community'],['Partner with us','Bring expertise, resources and reach to initiatives that matter.','/partners']].map(([title,copy,to])=><Link key={to} to={to as '/community'} className="group border-l-2 border-primary px-5 py-2"><h3 className="text-xl font-bold">{title}</h3><p className="mt-3 text-sm text-muted-foreground">{copy}</p><ArrowUpRight className="mt-7 size-5 text-primary transition-transform group-hover:translate-x-1"/></Link>)}</div></section></div>; }
