import { createFileRoute, Link } from '@tanstack/react-router';
import { PageIntro, SectionHeading, FeatureGrid } from '@/components/SectionUI';
import { pageHead } from '@/lib/prescribly-content';
import { Button } from '@/components/ui/button';
import { getPublicContent } from '@/lib/public-data.functions';
import hero from '@/assets/prescribly-events-hero.jpg';
const types=['Strategic Partner','Event Sponsor','Community Health Partner',"Women's Health Partner",'Youth & Education Partner','Technology Partner','Media Partner'];
export const Route=createFileRoute('/partners')({head:()=>pageHead('/partners','Partner With Prescribly','Connect your organization with healthcare events, community health, innovation and youth initiatives.'),loader:()=>getPublicContent(),errorComponent:()=> <p className="px-5 py-20">Partners could not be loaded.</p>,notFoundComponent:()=> <p className="px-5 py-20">Partners are unavailable.</p>,component:Partners});
function Partners(){const {partners}=Route.useLoaderData();return <div><PageIntro eyebrow="Partner With Us" title="LET'S BUILD SOMETHING BIGGER THAN AN EVENT." description="Our events and campaigns create opportunities for organizations to contribute expertise, resources, technology, funding and community reach." image={hero}/><section className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><SectionHeading eyebrow="Ways to collaborate" title="A partnership for every kind of contribution."/><div className="mt-10"><FeatureGrid items={types.map(x=>[x,'Collaborate with Prescribly Events on meaningful healthcare experiences and community programmes.'] as const)}/></div>{partners.length>0&&<div className="mt-16"><SectionHeading eyebrow="Our partners" title="Working together."/><div className="mt-8 grid gap-4 md:grid-cols-2">{partners.map(p=><article key={p.id} className="border border-border bg-card p-6"><p className="text-xs font-bold uppercase text-primary">{p.partnership_type}</p><h3 className="mt-4 text-2xl font-bold">{p.name}</h3><p className="mt-3 whitespace-pre-line text-muted-foreground">{p.description}</p>{p.website_url?.startsWith("https://")&&<a className="mt-4 inline-block text-sm font-bold text-primary" href={p.website_url} target="_blank" rel="noopener noreferrer">Visit website ↗</a>}</article>)}</div></div>}<div className="mt-10 flex gap-3"><Button asChild><Link to="/contact">Become a Partner</Link></Button><Button asChild variant="outline"><Link to="/sponsors">Explore Sponsorship</Link></Button></div></section></div>}
