import { createFileRoute, Link } from '@tanstack/react-router';
import { PageIntro, SectionHeading, FeatureGrid } from '@/components/SectionUI';
import { pageHead } from '@/lib/prescribly-content';
import { Button } from '@/components/ui/button';
import hero from '@/assets/prescribly-events-hero.jpg';
const support=['Healthcare screenings','Community health education',"Women's health initiatives",'Youth programs','Digital health sessions','Event production','Technology infrastructure','Educational materials','Community outreach'];
const benefits=['Logo placement','Event branding','Digital visibility','Speaking opportunities','Exhibition opportunities','Brand mentions','Social media exposure','Media opportunities','Community engagement','Post-event impact reporting'];
export const Route=createFileRoute('/sponsors')({head:()=>pageHead('/sponsors','Sponsor better healthcare','Support meaningful healthcare experiences while connecting with professionals, communities and innovators.'),component:Sponsors});
function Sponsors(){return <div><PageIntro eyebrow="Sponsorship" title="PUT YOUR BRAND BEHIND BETTER HEALTHCARE" description="Your organization can help create meaningful healthcare experiences while connecting with healthcare professionals, communities, young people and innovators." image={hero}/><section className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><SectionHeading eyebrow="Where support goes" title="Make participation possible."/><div className="mt-10"><FeatureGrid items={support.map(x=>[x,'A potential area of support for events and community programmes.'] as const)}/></div></section><section className="bg-secondary"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><SectionHeading eyebrow="Potential benefits" title="Visibility with purpose." copy="Sponsorship benefits are discussed and confirmed with each partner; none are guaranteed before an agreement."/><div className="mt-8 flex flex-wrap gap-2">{benefits.map(x=><span key={x} className="border border-border bg-card px-4 py-3 text-sm font-semibold">{x}</span>)}</div><div className="mt-10 flex flex-wrap gap-3"><Button asChild><Link to="/contact">Request Sponsorship Deck</Link></Button><Button asChild variant="outline"><Link to="/contact">Talk to the Partnerships Team</Link></Button></div></div></section></div>}
