import { useEffect, useState } from 'react';
import { useServerFn } from '@tanstack/react-start';
import { Plus, Pencil, Search, Save, RefreshCw } from 'lucide-react';
import { listAdminContent, saveAdminContent } from '@/lib/admin.functions';
import { editorFields, emptyRecord, normalizeRecord, type ContentTable, type ContentRecord } from '@/lib/content-editor';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Switch } from '@/components/ui/switch';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { toast } from 'sonner';

export function ContentManager({table,onSaved}:{table:ContentTable;onSaved:()=>void}) {
 const list=useServerFn(listAdminContent); const save=useServerFn(saveAdminContent);
 const [rows,setRows]=useState<ContentRecord[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [search,setSearch]=useState(''); const [record,setRecord]=useState<ContentRecord|null>(null); const [saving,setSaving]=useState(false);
 async function refresh(){setLoading(true);setError('');try{setRows(await list({data:{table}}) as ContentRecord[])}catch{setError('Could not load content. Please try again.')}finally{setLoading(false)}}
 useEffect(()=>{let cancelled=false;setLoading(true);list({data:{table}}).then(data=>{if(!cancelled)setRows(data as ContentRecord[])}).catch(()=>{if(!cancelled)setError('Could not load content. Please try again.')}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[table,list]);
 function edit(row:ContentRecord){const draft={...row};for(const f of editorFields[table])if(f.type==='datetime-local'&&draft[f.key]){const date=new Date(String(draft[f.key]));draft[f.key]=new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16)}setRecord(draft)}
 async function submit(e:React.FormEvent){e.preventDefault();if(!record)return;setSaving(true);try{await save({data:{table,id:typeof record.id==='string'?record.id:undefined,record:normalizeRecord(table,record)}});setRecord(null);toast.success('Content saved.');await refresh();onSaved()}catch(e){toast.error(e instanceof Error?e.message:'Could not save content.')}finally{setSaving(false)}}
 const filtered=rows.filter(row=>String(row.title??row.name??'').toLowerCase().includes(search.toLowerCase()));
 return <div className="mt-6"><div className="flex flex-wrap items-center justify-between gap-3"><div className="relative min-w-0 flex-1 sm:max-w-sm"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input aria-label="Search content" placeholder="Search content" value={search} onChange={e=>setSearch(e.target.value)} className="pl-9"/></div><div className="flex gap-2"><Button variant="outline" size="icon" title="Refresh" aria-label="Refresh content" onClick={refresh}><RefreshCw className={loading?'animate-spin':''}/></Button><Button onClick={()=>setRecord(emptyRecord(table))}><Plus/>Add {table==='campaigns'?'campaign':table.slice(0,-1)}</Button></div></div>{error?<p role="alert" className="mt-5 text-destructive">{error}</p>:loading?<p className="py-12 text-muted-foreground">Loading content…</p>:<div className="mt-6 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs uppercase text-muted-foreground"><th className="p-3">Title / Name</th><th className="p-3">Status</th><th className="p-3">Category / Type</th><th className="p-3"><span className="sr-only">Actions</span></th></tr></thead><tbody>{filtered.map(row=><tr key={String(row.id)} className="border-b"><td className="min-w-48 p-3 font-semibold">{String(row.title??row.name)}{row.slug&&<span className="mt-1 block text-xs font-normal text-muted-foreground">{String(row.slug)}</span>}</td><td className="p-3"><span className={row.status==='published'?'text-success':'text-muted-foreground'}>{String(row.status)}</span></td><td className="p-3">{String(row.category??row.partnership_type??'—')}</td><td className="p-3"><Button variant="ghost" size="icon" aria-label={`Edit ${row.title??row.name}`} title="Edit" onClick={()=>edit(row)}><Pencil/></Button></td></tr>)}</tbody></table>{!filtered.length&&<p className="py-12 text-center text-muted-foreground">{search?'No matching content.':'No content yet.'}</p>}</div>}
 <Dialog open={!!record} onOpenChange={open=>{if(!open&&!saving)setRecord(null)}}><DialogContent className="max-h-[85dvh] w-[calc(100%-2rem)] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>{record?.id?'Edit':'Add'} {table==='campaigns'?'campaign':table.slice(0,-1)}</DialogTitle><DialogDescription>Only published content is shown publicly. Keep unconfirmed details marked to be announced.</DialogDescription></DialogHeader>{record&&<form onSubmit={submit} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2">{editorFields[table].map(f=><div key={f.key} className={f.multiline?'sm:col-span-2':''}><label htmlFor={`edit-${f.key}`} className="mb-2 block text-sm font-semibold">{f.label}{f.required?' *':''}</label>{f.options?<Select value={String(record[f.key]??f.options[0])} onValueChange={v=>setRecord({...record,[f.key]:v})}><SelectTrigger id={`edit-${f.key}`}><SelectValue/></SelectTrigger><SelectContent>{f.options.map(v=><SelectItem key={v} value={v}>{v.replaceAll('_',' ')}</SelectItem>)}</SelectContent></Select>:f.multiline?<Textarea id={`edit-${f.key}`} rows={4} value={String(record[f.key]??'')} onChange={e=>setRecord({...record,[f.key]:e.target.value})}/>:<Input id={`edit-${f.key}`} type={f.type??'text'} required={f.required} min={f.type==='number'?0:undefined} step={f.key==='support_amount'?'0.01':undefined} value={String(record[f.key]??'')} onChange={e=>setRecord({...record,[f.key]:e.target.value})}/>}</div>)}</div>{(table==='events'||table==='campaigns')&&<div className="flex items-center gap-3"><Switch id="edit-featured" checked={!!record.featured} onCheckedChange={v=>setRecord({...record,featured:v})}/><label htmlFor="edit-featured" className="text-sm font-semibold">Featured</label></div>}<div className="flex justify-end gap-3 border-t pt-4"><Button type="button" variant="outline" disabled={saving} onClick={()=>setRecord(null)}>Cancel</Button><Button disabled={saving}><Save/>{saving?'Saving…':'Save changes'}</Button></div></form>}</DialogContent></Dialog></div>;
}