import { Link } from '@tanstack/react-router';
import { ArrowRight, CalendarDays, MapPin } from 'lucide-react';
import type { ReactNode } from 'react';
import { Button } from '@/components/ui/button';

export function Eyebrow({ children }: { children: ReactNode }) { return <span className="text-xs font-bold uppercase text-primary">{children}</span>; }
export function PageIntro({ eyebrow, title, description, image }: { eyebrow:string; title:string; description:string; image?:string }) {
  return <section className="relative isolate overflow-hidden bg-foreground text-primary-foreground"><div className="absolute inset-0 opacity-35">{image && <img src={image} alt="" className="h-full w-full object-cover" />}</div><div className="absolute inset-0 bg-foreground/50" /><div className="relative mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><span className="text-xs font-bold uppercase text-signal">{eyebrow}</span><h1 className="mt-5 max-w-5xl text-4xl font-bold leading-tight sm:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-base leading-relaxed text-primary-foreground/85 sm:text-lg">{description}</p></div></section>;
}
export function SectionHeading({ eyebrow, title, copy }: { eyebrow?: string; title:string; copy?:string }) { return <div className="max-w-3xl">{eyebrow && <Eyebrow>{eyebrow}</Eyebrow>}<h2 className="mt-3 text-3xl font-bold leading-tight sm:text-5xl">{title}</h2>{copy && <p className="mt-5 text-base leading-relaxed text-muted-foreground">{copy}</p>}</div>; }
export function FeatureGrid({ items, columns = 3 }: { items: readonly (readonly [string,string])[]; columns?:2|3 }) { return <div className={`grid gap-4 ${columns === 2 ? 'md:grid-cols-2' : 'md:grid-cols-2 lg:grid-cols-3'}`}>{items.map(([title,copy], i) => <article key={title} className="border-t border-border bg-card px-5 py-7"><span className="text-xs font-semibold text-primary">{String(i+1).padStart(2,'0')}</span><h3 className="mt-8 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{copy}</p></article>)}</div>; }
export function ActionLink({ to, children, secondary = false }: {to:string;children:ReactNode;secondary?:boolean}) { return <Button asChild variant={secondary ? 'outline' : 'default'} size="lg" className="h-12 px-6"><Link to={to as '/events'}>{children}<ArrowRight /></Link></Button>; }
export function EventCard({ title, subtitle, category, location, href, date = 'Date to be announced', status = 'Details coming soon' }: {title:string;subtitle?:string;category:string;location?:string;href:string;date?:string;status?:string}) { return <article className="flex h-full flex-col border border-border bg-card p-6"><div className="flex items-center justify-between gap-3"><span className="text-xs font-bold uppercase text-primary">{category}</span><span className="text-xs text-muted-foreground">{status}</span></div><h3 className="mt-8 text-2xl font-bold">{title}</h3>{subtitle && <p className="mt-3 text-muted-foreground">{subtitle}</p>}<div className="mt-auto pt-7 text-sm text-muted-foreground"><p className="flex items-center gap-2"><CalendarDays className="size-4" />{date}</p>{location && <p className="mt-2 flex items-center gap-2"><MapPin className="size-4" />{location}</p>}</div><Link to={href as '/events'} className="mt-7 flex items-center justify-between border-t border-border pt-4 text-sm font-bold text-primary">Explore <ArrowRight className="size-4" /></Link></article>; }
