import { Link } from '@tanstack/react-router';
import { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
const GROUPS = [ ['Explore', [['Events','/events'],['Campaigns','/campaigns'],['Community','/community'],['Impact','/impact'],['Speakers','/speakers']]], ['Get involved', [['Register','/register'],['Partner With Us','/partners'],['Sponsorship','/sponsors'],['Contact','/contact'],['PadAndFresh','/campaigns/padandfresh']]] ] as const;
export function SiteFooter() {
 const [email,setEmail]=useState(''); const [busy,setBusy]=useState(false);
 async function subscribe(e:React.FormEvent) { e.preventDefault(); if (!email.includes('@')) return; setBusy(true); const {error}=await supabase.from('newsletter_subscribers').insert({email:email.trim()}); setBusy(false); if (error && !error.message.includes('duplicate')) toast.error('Could not subscribe. Please try again.'); else {toast.success('You are subscribed.');setEmail('');} }
 return <footer className="mt-20 bg-foreground text-primary-foreground"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-16 sm:px-8 md:grid-cols-2 lg:grid-cols-4"><div><Link to="/" className="text-xl font-black">PRESCRIBLY<span className="text-signal">.</span> EVENTS</Link><p className="mt-5 text-sm text-primary-foreground/70">Conversations. Communities.<br/>Healthcare. Impact.</p><p className="mt-7 text-xs font-bold uppercase text-signal">A Prescribly Initiative</p></div>{GROUPS.map(([heading,links])=><div key={heading}><h2 className="mb-5 text-sm font-bold uppercase text-signal">{heading}</h2><ul className="space-y-3">{links.map(([label,to])=><li key={to}><Link to={to} className="text-sm text-primary-foreground/75 hover:text-primary-foreground">{label}</Link></li>)}</ul></div>)}<div><h2 className="mb-5 text-sm font-bold uppercase text-signal">Stay connected</h2><p className="mb-4 text-sm text-primary-foreground/70">Ideas and opportunities from the Prescribly community.</p><form onSubmit={subscribe} className="flex gap-2"><input aria-label="Email for updates" required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" className="min-w-0 flex-1 border border-primary-foreground/30 bg-transparent px-3 py-2 text-sm text-primary-foreground placeholder:text-primary-foreground/50"/><Button type="submit" disabled={busy} variant="secondary">Join</Button></form><Link to="/contact" className="mt-6 block text-sm text-primary-foreground/75 hover:underline">Contact the team</Link></div></div><div className="border-t border-primary-foreground/20"><div className="mx-auto flex max-w-7xl flex-wrap justify-between gap-3 px-5 py-6 text-xs text-primary-foreground/60 sm:px-8"><span>© 2026 Prescribly Limited. All rights reserved.</span><span>Healthcare information on this site is educational, not medical advice.</span></div></div></footer>;
}
