import { Link, useRouterState } from '@tanstack/react-router';
import { useState } from 'react';
import { ArrowUpRight, Menu, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
const NAV = [ ['/','Home'], ['/events','Events'], ['/campaigns','Campaigns'], ['/community','Community'], ['/impact','Impact'], ['/about','About'], ['/partners','Partner With Us'] ] as const;
export function SiteHeader() {
  const [open,setOpen] = useState(false);
  const pathname = useRouterState({ select:s => s.location.pathname });
  return <header className="sticky top-0 z-50 border-b border-border bg-background/95 backdrop-blur-lg"><div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between gap-5 px-5 sm:px-8"><Link to="/" onClick={() => setOpen(false)} className="flex shrink-0 items-center gap-3"><span className="grid size-9 place-items-center rounded-sm bg-primary text-lg font-black text-primary-foreground">P<span className="text-signal">.</span></span><span className="leading-none"><strong className="block text-lg font-extrabold">PRESCRIBLY</strong><span className="block pt-1 text-[10px] font-bold uppercase text-primary">Events</span></span></Link><nav aria-label="Main navigation" className="hidden items-center gap-4 xl:flex">{NAV.map(([to,label]) => <Link key={to} to={to} className={`text-xs font-semibold transition-colors hover:text-primary ${pathname === to ? 'text-primary' : 'text-muted-foreground'}`}>{label}</Link>)}</nav><div className="hidden items-center gap-2 md:flex"><Button asChild size="sm" variant="outline" className="hidden lg:inline-flex"><Link to="/partners">Partner With Us</Link></Button><Button asChild className="h-10 px-4 text-xs font-bold uppercase"><Link to="/register">Register for an Event <ArrowUpRight /></Link></Button></div><Button variant="ghost" size="icon" aria-label={open ? 'Close menu' : 'Open menu'} aria-expanded={open} onClick={() => setOpen(!open)} className="xl:hidden">{open ? <X /> : <Menu />}</Button></div>{open && <nav aria-label="Mobile navigation" className="border-t border-border bg-background px-5 py-4 xl:hidden"><div className="mx-auto grid max-w-7xl gap-1 sm:grid-cols-2">{NAV.map(([to,label]) => <Link key={to} to={to} onClick={() => setOpen(false)} className="border-b border-border px-2 py-3 text-sm font-semibold">{label}</Link>)}<Link to="/register" onClick={() => setOpen(false)} className="mt-3 bg-primary px-4 py-3 text-center text-sm font-bold text-primary-foreground">Register for an Event</Link></div></nav>}</header>;
}
