/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as PadATeenageGirlRouteImport } from './routes/pad-a-teenage-girl'
import { Route as GuardATeenageBoyRouteImport } from './routes/guard-a-teenage-boy'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsYouthDigitalHealthRouteImport } from './routes/events.youth-digital-health'
import { Route as EventsWomensHealthRouteImport } from './routes/events.womens-health'
import { Route as EventsWebinarsRouteImport } from './routes/events.webinars'
import { Route as EventsOnlineConversationsRouteImport } from './routes/events.online-conversations'
import { Route as EventsHealthFuturesRouteImport } from './routes/events.health-futures'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const PadATeenageGirlRoute = PadATeenageGirlRouteImport.update({
  id: '/pad-a-teenage-girl',
  path: '/pad-a-teenage-girl',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardATeenageBoyRoute = GuardATeenageBoyRouteImport.update({
  id: '/guard-a-teenage-boy',
  path: '/guard-a-teenage-boy',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const EventsYouthDigitalHealthRoute =
  EventsYouthDigitalHealthRouteImport.update({
    id: '/youth-digital-health',
    path: '/youth-digital-health',
    getParentRoute: () => EventsRoute,
  } as any)
const EventsWomensHealthRoute = EventsWomensHealthRouteImport.update({
  id: '/womens-health',
  path: '/womens-health',
  getParentRoute: () => EventsRoute,
} as any)
const EventsWebinarsRoute = EventsWebinarsRouteImport.update({
  id: '/webinars',
  path: '/webinars',
  getParentRoute: () => EventsRoute,
} as any)
const EventsOnlineConversationsRoute =
  EventsOnlineConversationsRouteImport.update({
    id: '/online-conversations',
    path: '/online-conversations',
    getParentRoute: () => EventsRoute,
  } as any)
const EventsHealthFuturesRoute = EventsHealthFuturesRouteImport.update({
  id: '/health-futures',
  path: '/health-futures',
  getParentRoute: () => EventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRouteWithChildren
  '/guard-a-teenage-boy': typeof GuardATeenageBoyRoute
  '/pad-a-teenage-girl': typeof PadATeenageGirlRoute
  '/thank-you': typeof ThankYouRoute
  '/events/health-futures': typeof EventsHealthFuturesRoute
  '/events/online-conversations': typeof EventsOnlineConversationsRoute
  '/events/webinars': typeof EventsWebinarsRoute
  '/events/womens-health': typeof EventsWomensHealthRoute
  '/events/youth-digital-health': typeof EventsYouthDigitalHealthRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/guard-a-teenage-boy': typeof GuardATeenageBoyRoute
  '/pad-a-teenage-girl': typeof PadATeenageGirlRoute
  '/thank-you': typeof ThankYouRoute
  '/events/health-futures': typeof EventsHealthFuturesRoute
  '/events/online-conversations': typeof EventsOnlineConversationsRoute
  '/events/webinars': typeof EventsWebinarsRoute
  '/events/womens-health': typeof EventsWomensHealthRoute
  '/events/youth-digital-health': typeof EventsYouthDigitalHealthRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRouteWithChildren
  '/guard-a-teenage-boy': typeof GuardATeenageBoyRoute
  '/pad-a-teenage-girl': typeof PadATeenageGirlRoute
  '/thank-you': typeof ThankYouRoute
  '/events/health-futures': typeof EventsHealthFuturesRoute
  '/events/online-conversations': typeof EventsOnlineConversationsRoute
  '/events/webinars': typeof EventsWebinarsRoute
  '/events/womens-health': typeof EventsWomensHealthRoute
  '/events/youth-digital-health': typeof EventsYouthDigitalHealthRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/donate'
    | '/events'
    | '/guard-a-teenage-boy'
    | '/pad-a-teenage-girl'
    | '/thank-you'
    | '/events/health-futures'
    | '/events/online-conversations'
    | '/events/webinars'
    | '/events/womens-health'
    | '/events/youth-digital-health'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/donate'
    | '/guard-a-teenage-boy'
    | '/pad-a-teenage-girl'
    | '/thank-you'
    | '/events/health-futures'
    | '/events/online-conversations'
    | '/events/webinars'
    | '/events/womens-health'
    | '/events/youth-digital-health'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/donate'
    | '/events'
    | '/guard-a-teenage-boy'
    | '/pad-a-teenage-girl'
    | '/thank-you'
    | '/events/health-futures'
    | '/events/online-conversations'
    | '/events/webinars'
    | '/events/womens-health'
    | '/events/youth-digital-health'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRouteWithChildren
  GuardATeenageBoyRoute: typeof GuardATeenageBoyRoute
  PadATeenageGirlRoute: typeof PadATeenageGirlRoute
  ThankYouRoute: typeof ThankYouRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pad-a-teenage-girl': {
      id: '/pad-a-teenage-girl'
      path: '/pad-a-teenage-girl'
      fullPath: '/pad-a-teenage-girl'
      preLoaderRoute: typeof PadATeenageGirlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guard-a-teenage-boy': {
      id: '/guard-a-teenage-boy'
      path: '/guard-a-teenage-boy'
      fullPath: '/guard-a-teenage-boy'
      preLoaderRoute: typeof GuardATeenageBoyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/youth-digital-health': {
      id: '/events/youth-digital-health'
      path: '/youth-digital-health'
      fullPath: '/events/youth-digital-health'
      preLoaderRoute: typeof EventsYouthDigitalHealthRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/womens-health': {
      id: '/events/womens-health'
      path: '/womens-health'
      fullPath: '/events/womens-health'
      preLoaderRoute: typeof EventsWomensHealthRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/webinars': {
      id: '/events/webinars'
      path: '/webinars'
      fullPath: '/events/webinars'
      preLoaderRoute: typeof EventsWebinarsRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/online-conversations': {
      id: '/events/online-conversations'
      path: '/online-conversations'
      fullPath: '/events/online-conversations'
      preLoaderRoute: typeof EventsOnlineConversationsRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/health-futures': {
      id: '/events/health-futures'
      path: '/health-futures'
      fullPath: '/events/health-futures'
      preLoaderRoute: typeof EventsHealthFuturesRouteImport
      parentRoute: typeof EventsRoute
    }
  }
}

interface EventsRouteChildren {
  EventsHealthFuturesRoute: typeof EventsHealthFuturesRoute
  EventsOnlineConversationsRoute: typeof EventsOnlineConversationsRoute
  EventsWebinarsRoute: typeof EventsWebinarsRoute
  EventsWomensHealthRoute: typeof EventsWomensHealthRoute
  EventsYouthDigitalHealthRoute: typeof EventsYouthDigitalHealthRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsHealthFuturesRoute: EventsHealthFuturesRoute,
  EventsOnlineConversationsRoute: EventsOnlineConversationsRoute,
  EventsWebinarsRoute: EventsWebinarsRoute,
  EventsWomensHealthRoute: EventsWomensHealthRoute,
  EventsYouthDigitalHealthRoute: EventsYouthDigitalHealthRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRouteWithChildren,
  GuardATeenageBoyRoute: GuardATeenageBoyRoute,
  PadATeenageGirlRoute: PadATeenageGirlRoute,
  ThankYouRoute: ThankYouRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
