/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SpeakersRouteImport } from './routes/speakers'
import { Route as RegistrationSuccessRouteImport } from './routes/registration-success'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PadATeenageGirlRouteImport } from './routes/pad-a-teenage-girl'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as GuardATeenageBoyRouteImport } from './routes/guard-a-teenage-boy'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as EventsYouthDigitalHealthRouteImport } from './routes/events.youth-digital-health'
import { Route as EventsWomensHealthRouteImport } from './routes/events.womens-health'
import { Route as EventsWebinarsRouteImport } from './routes/events.webinars'
import { Route as EventsOnlineConversationsRouteImport } from './routes/events.online-conversations'
import { Route as EventsKadunaDigitalHealthWellnessWeek2027RouteImport } from './routes/events.kaduna-digital-health-wellness-week-2027'
import { Route as EventsHealthFuturesRouteImport } from './routes/events.health-futures'
import { Route as CampaignsYouthDigitalHealthRouteImport } from './routes/campaigns.youth-digital-health'
import { Route as CampaignsWomensHealthRouteImport } from './routes/campaigns.womens-health'
import { Route as CampaignsPadandfreshRouteImport } from './routes/campaigns.padandfresh'
import { Route as CampaignsCommunityHealthRouteImport } from './routes/campaigns.community-health'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as CampaignsPadandfreshIndexRouteImport } from './routes/campaigns.padandfresh.index'
import { Route as EventsDetailsSlugRouteImport } from './routes/events.details.$slug'
import { Route as CampaignsPadandfreshPadAGirlRouteImport } from './routes/campaigns.padandfresh.pad-a-girl'
import { Route as CampaignsPadandfreshGuardABoyRouteImport } from './routes/campaigns.padandfresh.guard-a-boy'
import { Route as CampaignsDetailsSlugRouteImport } from './routes/campaigns.details.$slug'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersRoute = SpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationSuccessRoute = RegistrationSuccessRouteImport.update({
  id: '/registration-success',
  path: '/registration-success',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PadATeenageGirlRoute = PadATeenageGirlRouteImport.update({
  id: '/pad-a-teenage-girl',
  path: '/pad-a-teenage-girl',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardATeenageBoyRoute = GuardATeenageBoyRouteImport.update({
  id: '/guard-a-teenage-boy',
  path: '/guard-a-teenage-boy',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsRoute,
} as any)
const EventsYouthDigitalHealthRoute =
  EventsYouthDigitalHealthRouteImport.update({
    id: '/youth-digital-health',
    path: '/youth-digital-health',
    getParentRoute: () => EventsRoute,
  } as any)
const EventsWomensHealthRoute = EventsWomensHealthRouteImport.update({
  id: '/womens-health',
  path: '/womens-health',
  getParentRoute: () => EventsRoute,
} as any)
const EventsWebinarsRoute = EventsWebinarsRouteImport.update({
  id: '/webinars',
  path: '/webinars',
  getParentRoute: () => EventsRoute,
} as any)
const EventsOnlineConversationsRoute =
  EventsOnlineConversationsRouteImport.update({
    id: '/online-conversations',
    path: '/online-conversations',
    getParentRoute: () => EventsRoute,
  } as any)
const EventsKadunaDigitalHealthWellnessWeek2027Route =
  EventsKadunaDigitalHealthWellnessWeek2027RouteImport.update({
    id: '/kaduna-digital-health-wellness-week-2027',
    path: '/kaduna-digital-health-wellness-week-2027',
    getParentRoute: () => EventsRoute,
  } as any)
const EventsHealthFuturesRoute = EventsHealthFuturesRouteImport.update({
  id: '/health-futures',
  path: '/health-futures',
  getParentRoute: () => EventsRoute,
} as any)
const CampaignsYouthDigitalHealthRoute =
  CampaignsYouthDigitalHealthRouteImport.update({
    id: '/youth-digital-health',
    path: '/youth-digital-health',
    getParentRoute: () => CampaignsRoute,
  } as any)
const CampaignsWomensHealthRoute = CampaignsWomensHealthRouteImport.update({
  id: '/womens-health',
  path: '/womens-health',
  getParentRoute: () => CampaignsRoute,
} as any)
const CampaignsPadandfreshRoute = CampaignsPadandfreshRouteImport.update({
  id: '/padandfresh',
  path: '/padandfresh',
  getParentRoute: () => CampaignsRoute,
} as any)
const CampaignsCommunityHealthRoute =
  CampaignsCommunityHealthRouteImport.update({
    id: '/community-health',
    path: '/community-health',
    getParentRoute: () => CampaignsRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CampaignsPadandfreshIndexRoute =
  CampaignsPadandfreshIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CampaignsPadandfreshRoute,
  } as any)
const EventsDetailsSlugRoute = EventsDetailsSlugRouteImport.update({
  id: '/details/$slug',
  path: '/details/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const CampaignsPadandfreshPadAGirlRoute =
  CampaignsPadandfreshPadAGirlRouteImport.update({
    id: '/pad-a-girl',
    path: '/pad-a-girl',
    getParentRoute: () => CampaignsPadandfreshRoute,
  } as any)
const CampaignsPadandfreshGuardABoyRoute =
  CampaignsPadandfreshGuardABoyRouteImport.update({
    id: '/guard-a-boy',
    path: '/guard-a-boy',
    getParentRoute: () => CampaignsPadandfreshRoute,
  } as any)
const CampaignsDetailsSlugRoute = CampaignsDetailsSlugRouteImport.update({
  id: '/details/$slug',
  path: '/details/$slug',
  getParentRoute: () => CampaignsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRouteWithChildren
  '/guard-a-teenage-boy': typeof GuardATeenageBoyRoute
  '/impact': typeof ImpactRoute
  '/pad-a-teenage-girl': typeof PadATeenageGirlRoute
  '/partners': typeof PartnersRoute
  '/register': typeof RegisterRoute
  '/registration-success': typeof RegistrationSuccessRoute
  '/speakers': typeof SpeakersRoute
  '/sponsors': typeof SponsorsRoute
  '/thank-you': typeof ThankYouRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/campaigns/community-health': typeof CampaignsCommunityHealthRoute
  '/campaigns/padandfresh': typeof CampaignsPadandfreshRouteWithChildren
  '/campaigns/womens-health': typeof CampaignsWomensHealthRoute
  '/campaigns/youth-digital-health': typeof CampaignsYouthDigitalHealthRoute
  '/events/health-futures': typeof EventsHealthFuturesRoute
  '/events/kaduna-digital-health-wellness-week-2027': typeof EventsKadunaDigitalHealthWellnessWeek2027Route
  '/events/online-conversations': typeof EventsOnlineConversationsRoute
  '/events/webinars': typeof EventsWebinarsRoute
  '/events/womens-health': typeof EventsWomensHealthRoute
  '/events/youth-digital-health': typeof EventsYouthDigitalHealthRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/campaigns/details/$slug': typeof CampaignsDetailsSlugRoute
  '/campaigns/padandfresh/guard-a-boy': typeof CampaignsPadandfreshGuardABoyRoute
  '/campaigns/padandfresh/pad-a-girl': typeof CampaignsPadandfreshPadAGirlRoute
  '/events/details/$slug': typeof EventsDetailsSlugRoute
  '/campaigns/padandfresh/': typeof CampaignsPadandfreshIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/guard-a-teenage-boy': typeof GuardATeenageBoyRoute
  '/impact': typeof ImpactRoute
  '/pad-a-teenage-girl': typeof PadATeenageGirlRoute
  '/partners': typeof PartnersRoute
  '/register': typeof RegisterRoute
  '/registration-success': typeof RegistrationSuccessRoute
  '/speakers': typeof SpeakersRoute
  '/sponsors': typeof SponsorsRoute
  '/thank-you': typeof ThankYouRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/campaigns/community-health': typeof CampaignsCommunityHealthRoute
  '/campaigns/womens-health': typeof CampaignsWomensHealthRoute
  '/campaigns/youth-digital-health': typeof CampaignsYouthDigitalHealthRoute
  '/events/health-futures': typeof EventsHealthFuturesRoute
  '/events/kaduna-digital-health-wellness-week-2027': typeof EventsKadunaDigitalHealthWellnessWeek2027Route
  '/events/online-conversations': typeof EventsOnlineConversationsRoute
  '/events/webinars': typeof EventsWebinarsRoute
  '/events/womens-health': typeof EventsWomensHealthRoute
  '/events/youth-digital-health': typeof EventsYouthDigitalHealthRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/events': typeof EventsIndexRoute
  '/campaigns/details/$slug': typeof CampaignsDetailsSlugRoute
  '/campaigns/padandfresh/guard-a-boy': typeof CampaignsPadandfreshGuardABoyRoute
  '/campaigns/padandfresh/pad-a-girl': typeof CampaignsPadandfreshPadAGirlRoute
  '/events/details/$slug': typeof EventsDetailsSlugRoute
  '/campaigns/padandfresh': typeof CampaignsPadandfreshIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRouteWithChildren
  '/guard-a-teenage-boy': typeof GuardATeenageBoyRoute
  '/impact': typeof ImpactRoute
  '/pad-a-teenage-girl': typeof PadATeenageGirlRoute
  '/partners': typeof PartnersRoute
  '/register': typeof RegisterRoute
  '/registration-success': typeof RegistrationSuccessRoute
  '/speakers': typeof SpeakersRoute
  '/sponsors': typeof SponsorsRoute
  '/thank-you': typeof ThankYouRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/campaigns/community-health': typeof CampaignsCommunityHealthRoute
  '/campaigns/padandfresh': typeof CampaignsPadandfreshRouteWithChildren
  '/campaigns/womens-health': typeof CampaignsWomensHealthRoute
  '/campaigns/youth-digital-health': typeof CampaignsYouthDigitalHealthRoute
  '/events/health-futures': typeof EventsHealthFuturesRoute
  '/events/kaduna-digital-health-wellness-week-2027': typeof EventsKadunaDigitalHealthWellnessWeek2027Route
  '/events/online-conversations': typeof EventsOnlineConversationsRoute
  '/events/webinars': typeof EventsWebinarsRoute
  '/events/womens-health': typeof EventsWomensHealthRoute
  '/events/youth-digital-health': typeof EventsYouthDigitalHealthRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/campaigns/details/$slug': typeof CampaignsDetailsSlugRoute
  '/campaigns/padandfresh/guard-a-boy': typeof CampaignsPadandfreshGuardABoyRoute
  '/campaigns/padandfresh/pad-a-girl': typeof CampaignsPadandfreshPadAGirlRoute
  '/events/details/$slug': typeof EventsDetailsSlugRoute
  '/campaigns/padandfresh/': typeof CampaignsPadandfreshIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/campaigns'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/donate'
    | '/events'
    | '/guard-a-teenage-boy'
    | '/impact'
    | '/pad-a-teenage-girl'
    | '/partners'
    | '/register'
    | '/registration-success'
    | '/speakers'
    | '/sponsors'
    | '/thank-you'
    | '/admin'
    | '/campaigns/community-health'
    | '/campaigns/padandfresh'
    | '/campaigns/womens-health'
    | '/campaigns/youth-digital-health'
    | '/events/health-futures'
    | '/events/kaduna-digital-health-wellness-week-2027'
    | '/events/online-conversations'
    | '/events/webinars'
    | '/events/womens-health'
    | '/events/youth-digital-health'
    | '/campaigns/'
    | '/events/'
    | '/campaigns/details/$slug'
    | '/campaigns/padandfresh/guard-a-boy'
    | '/campaigns/padandfresh/pad-a-girl'
    | '/events/details/$slug'
    | '/campaigns/padandfresh/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/donate'
    | '/guard-a-teenage-boy'
    | '/impact'
    | '/pad-a-teenage-girl'
    | '/partners'
    | '/register'
    | '/registration-success'
    | '/speakers'
    | '/sponsors'
    | '/thank-you'
    | '/admin'
    | '/campaigns/community-health'
    | '/campaigns/womens-health'
    | '/campaigns/youth-digital-health'
    | '/events/health-futures'
    | '/events/kaduna-digital-health-wellness-week-2027'
    | '/events/online-conversations'
    | '/events/webinars'
    | '/events/womens-health'
    | '/events/youth-digital-health'
    | '/campaigns'
    | '/events'
    | '/campaigns/details/$slug'
    | '/campaigns/padandfresh/guard-a-boy'
    | '/campaigns/padandfresh/pad-a-girl'
    | '/events/details/$slug'
    | '/campaigns/padandfresh'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/campaigns'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/donate'
    | '/events'
    | '/guard-a-teenage-boy'
    | '/impact'
    | '/pad-a-teenage-girl'
    | '/partners'
    | '/register'
    | '/registration-success'
    | '/speakers'
    | '/sponsors'
    | '/thank-you'
    | '/_authenticated/admin'
    | '/campaigns/community-health'
    | '/campaigns/padandfresh'
    | '/campaigns/womens-health'
    | '/campaigns/youth-digital-health'
    | '/events/health-futures'
    | '/events/kaduna-digital-health-wellness-week-2027'
    | '/events/online-conversations'
    | '/events/webinars'
    | '/events/womens-health'
    | '/events/youth-digital-health'
    | '/campaigns/'
    | '/events/'
    | '/campaigns/details/$slug'
    | '/campaigns/padandfresh/guard-a-boy'
    | '/campaigns/padandfresh/pad-a-girl'
    | '/events/details/$slug'
    | '/campaigns/padandfresh/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CampaignsRoute: typeof CampaignsRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRouteWithChildren
  GuardATeenageBoyRoute: typeof GuardATeenageBoyRoute
  ImpactRoute: typeof ImpactRoute
  PadATeenageGirlRoute: typeof PadATeenageGirlRoute
  PartnersRoute: typeof PartnersRoute
  RegisterRoute: typeof RegisterRoute
  RegistrationSuccessRoute: typeof RegistrationSuccessRoute
  SpeakersRoute: typeof SpeakersRoute
  SponsorsRoute: typeof SponsorsRoute
  ThankYouRoute: typeof ThankYouRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers': {
      id: '/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof SpeakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration-success': {
      id: '/registration-success'
      path: '/registration-success'
      fullPath: '/registration-success'
      preLoaderRoute: typeof RegistrationSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pad-a-teenage-girl': {
      id: '/pad-a-teenage-girl'
      path: '/pad-a-teenage-girl'
      fullPath: '/pad-a-teenage-girl'
      preLoaderRoute: typeof PadATeenageGirlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guard-a-teenage-boy': {
      id: '/guard-a-teenage-boy'
      path: '/guard-a-teenage-boy'
      fullPath: '/guard-a-teenage-boy'
      preLoaderRoute: typeof GuardATeenageBoyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/events/youth-digital-health': {
      id: '/events/youth-digital-health'
      path: '/youth-digital-health'
      fullPath: '/events/youth-digital-health'
      preLoaderRoute: typeof EventsYouthDigitalHealthRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/womens-health': {
      id: '/events/womens-health'
      path: '/womens-health'
      fullPath: '/events/womens-health'
      preLoaderRoute: typeof EventsWomensHealthRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/webinars': {
      id: '/events/webinars'
      path: '/webinars'
      fullPath: '/events/webinars'
      preLoaderRoute: typeof EventsWebinarsRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/online-conversations': {
      id: '/events/online-conversations'
      path: '/online-conversations'
      fullPath: '/events/online-conversations'
      preLoaderRoute: typeof EventsOnlineConversationsRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/kaduna-digital-health-wellness-week-2027': {
      id: '/events/kaduna-digital-health-wellness-week-2027'
      path: '/kaduna-digital-health-wellness-week-2027'
      fullPath: '/events/kaduna-digital-health-wellness-week-2027'
      preLoaderRoute: typeof EventsKadunaDigitalHealthWellnessWeek2027RouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/health-futures': {
      id: '/events/health-futures'
      path: '/health-futures'
      fullPath: '/events/health-futures'
      preLoaderRoute: typeof EventsHealthFuturesRouteImport
      parentRoute: typeof EventsRoute
    }
    '/campaigns/youth-digital-health': {
      id: '/campaigns/youth-digital-health'
      path: '/youth-digital-health'
      fullPath: '/campaigns/youth-digital-health'
      preLoaderRoute: typeof CampaignsYouthDigitalHealthRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/campaigns/womens-health': {
      id: '/campaigns/womens-health'
      path: '/womens-health'
      fullPath: '/campaigns/womens-health'
      preLoaderRoute: typeof CampaignsWomensHealthRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/campaigns/padandfresh': {
      id: '/campaigns/padandfresh'
      path: '/padandfresh'
      fullPath: '/campaigns/padandfresh'
      preLoaderRoute: typeof CampaignsPadandfreshRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/campaigns/community-health': {
      id: '/campaigns/community-health'
      path: '/community-health'
      fullPath: '/campaigns/community-health'
      preLoaderRoute: typeof CampaignsCommunityHealthRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/campaigns/padandfresh/': {
      id: '/campaigns/padandfresh/'
      path: '/'
      fullPath: '/campaigns/padandfresh/'
      preLoaderRoute: typeof CampaignsPadandfreshIndexRouteImport
      parentRoute: typeof CampaignsPadandfreshRoute
    }
    '/events/details/$slug': {
      id: '/events/details/$slug'
      path: '/details/$slug'
      fullPath: '/events/details/$slug'
      preLoaderRoute: typeof EventsDetailsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/campaigns/padandfresh/pad-a-girl': {
      id: '/campaigns/padandfresh/pad-a-girl'
      path: '/pad-a-girl'
      fullPath: '/campaigns/padandfresh/pad-a-girl'
      preLoaderRoute: typeof CampaignsPadandfreshPadAGirlRouteImport
      parentRoute: typeof CampaignsPadandfreshRoute
    }
    '/campaigns/padandfresh/guard-a-boy': {
      id: '/campaigns/padandfresh/guard-a-boy'
      path: '/guard-a-boy'
      fullPath: '/campaigns/padandfresh/guard-a-boy'
      preLoaderRoute: typeof CampaignsPadandfreshGuardABoyRouteImport
      parentRoute: typeof CampaignsPadandfreshRoute
    }
    '/campaigns/details/$slug': {
      id: '/campaigns/details/$slug'
      path: '/details/$slug'
      fullPath: '/campaigns/details/$slug'
      preLoaderRoute: typeof CampaignsDetailsSlugRouteImport
      parentRoute: typeof CampaignsRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CampaignsPadandfreshRouteChildren {
  CampaignsPadandfreshGuardABoyRoute: typeof CampaignsPadandfreshGuardABoyRoute
  CampaignsPadandfreshPadAGirlRoute: typeof CampaignsPadandfreshPadAGirlRoute
  CampaignsPadandfreshIndexRoute: typeof CampaignsPadandfreshIndexRoute
}

const CampaignsPadandfreshRouteChildren: CampaignsPadandfreshRouteChildren = {
  CampaignsPadandfreshGuardABoyRoute: CampaignsPadandfreshGuardABoyRoute,
  CampaignsPadandfreshPadAGirlRoute: CampaignsPadandfreshPadAGirlRoute,
  CampaignsPadandfreshIndexRoute: CampaignsPadandfreshIndexRoute,
}

const CampaignsPadandfreshRouteWithChildren =
  CampaignsPadandfreshRoute._addFileChildren(CampaignsPadandfreshRouteChildren)

interface CampaignsRouteChildren {
  CampaignsCommunityHealthRoute: typeof CampaignsCommunityHealthRoute
  CampaignsPadandfreshRoute: typeof CampaignsPadandfreshRouteWithChildren
  CampaignsWomensHealthRoute: typeof CampaignsWomensHealthRoute
  CampaignsYouthDigitalHealthRoute: typeof CampaignsYouthDigitalHealthRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  CampaignsDetailsSlugRoute: typeof CampaignsDetailsSlugRoute
}

const CampaignsRouteChildren: CampaignsRouteChildren = {
  CampaignsCommunityHealthRoute: CampaignsCommunityHealthRoute,
  CampaignsPadandfreshRoute: CampaignsPadandfreshRouteWithChildren,
  CampaignsWomensHealthRoute: CampaignsWomensHealthRoute,
  CampaignsYouthDigitalHealthRoute: CampaignsYouthDigitalHealthRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  CampaignsDetailsSlugRoute: CampaignsDetailsSlugRoute,
}

const CampaignsRouteWithChildren = CampaignsRoute._addFileChildren(
  CampaignsRouteChildren,
)

interface EventsRouteChildren {
  EventsHealthFuturesRoute: typeof EventsHealthFuturesRoute
  EventsKadunaDigitalHealthWellnessWeek2027Route: typeof EventsKadunaDigitalHealthWellnessWeek2027Route
  EventsOnlineConversationsRoute: typeof EventsOnlineConversationsRoute
  EventsWebinarsRoute: typeof EventsWebinarsRoute
  EventsWomensHealthRoute: typeof EventsWomensHealthRoute
  EventsYouthDigitalHealthRoute: typeof EventsYouthDigitalHealthRoute
  EventsIndexRoute: typeof EventsIndexRoute
  EventsDetailsSlugRoute: typeof EventsDetailsSlugRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsHealthFuturesRoute: EventsHealthFuturesRoute,
  EventsKadunaDigitalHealthWellnessWeek2027Route:
    EventsKadunaDigitalHealthWellnessWeek2027Route,
  EventsOnlineConversationsRoute: EventsOnlineConversationsRoute,
  EventsWebinarsRoute: EventsWebinarsRoute,
  EventsWomensHealthRoute: EventsWomensHealthRoute,
  EventsYouthDigitalHealthRoute: EventsYouthDigitalHealthRoute,
  EventsIndexRoute: EventsIndexRoute,
  EventsDetailsSlugRoute: EventsDetailsSlugRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CampaignsRoute: CampaignsRouteWithChildren,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRouteWithChildren,
  GuardATeenageBoyRoute: GuardATeenageBoyRoute,
  ImpactRoute: ImpactRoute,
  PadATeenageGirlRoute: PadATeenageGirlRoute,
  PartnersRoute: PartnersRoute,
  RegisterRoute: RegisterRoute,
  RegistrationSuccessRoute: RegistrationSuccessRoute,
  SpeakersRoute: SpeakersRoute,
  SponsorsRoute: SponsorsRoute,
  ThankYouRoute: ThankYouRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
